### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by officialasishkumar** [Pashgunt/cdh#2] opened 2024-09-03 18:59 UTC
```
[00:28:19]  📁 /tmp/cdh   main  
$ make build-zsh                               
go build -o go-dir ./main.go && \
cp ./go-dir /usr/local/bin && \
    sudo sh -c "echo '' >> ~/.zshrc" && \
    sudo sh -c "cat ./bash/script.sh >> ~/.zshrc" && \
source ~/.zshrc
cp: cannot create regular file '/usr/local/bin/go-dir': Permission denied
make: *** [Makefile:5: build-zsh] Error 1
[00:28:27]  📁 /tmp/cdh   main  3s  ✘2 
$ sudo make build-zsh
[sudo] password for charon:     
go build -o go-dir ./main.go && \
cp ./go-dir /usr/local/bin && \
    sudo sh -c "echo '' >> ~/.zshrc" && \
    sudo sh -c "cat ./bash/script.sh >> ~/.zshrc" && \
source ~/.zshrc
/bin/sh: 5: source: not found
make: *** [Makefile:5: build-zsh] Error 127

```

Getting this error while trying to install cdh

**Comment by Pashgunt** [comment] 2024-09-03 19:13
Thank you, what is the error in the second case, I understood, if you want to try the project, then in order for it to unfold, you need to replace "source" with ".". I will correct this in the near future, I will try.

**Comment by officialasishkumar** [comment] 2024-09-03 19:40
@Pashgunt was wondering is sudo necessary for the code to run? If yes, can you add it in the readme.

**Comment by officialasishkumar** [comment] 2024-09-03 19:43
> you need to replace "source" with "."

Tried it but it's not working

makefile:
```
build-code:
	go build -o go-dir ./main.go && \
	cp ./go-dir /usr/local/bin
build-zsh:
	go build -o go-dir ./main.go && \
	cp ./go-dir /usr/local/bin && \
    sudo sh -c "echo '' >> ~/.zshrc" && \
    sudo sh -c "cat ./bash/script.sh >> ~/.zshrc" && \
	. ~/.zshrc

```

error: 
```
[00:28:40]  📁 /tmp/cdh   main  2s  ✘2 
$ sudo make build-zsh
[sudo] password for charon:     
go build -o go-dir ./main.go && \
cp ./go-dir /usr/local/bin && \
    sudo sh -c "echo '' >> ~/.zshrc" && \
    sudo sh -c "cat ./bash/script.sh >> ~/.zshrc" && \
. ~/.zshrc
/bin/sh: 2: /root/.zshrc: Syntax error: "(" unexpected
make: *** [Makefile:5: build-zsh] Error 2
```

**Comment by Pashgunt** [comment] 2024-09-03 19:46
> @Pashgunt was wondering is sudo necessary for the code to run? If yes, can you add it in the readme.

Yes, I will add

**Comment by Pashgunt** [comment] 2024-09-03 19:50
> > you need to replace "source" with "."
> 
> 
> 
> Tried it but it's not working
> 
> 
> 
> makefile:
> 
> ```
> 
> build-code:
> 
> 	go build -o go-dir ./main.go && \
> 
> 	cp ./go-dir /usr/local/bin
> 
> build-zsh:
> 
> 	go build -o go-dir ./main.go && \
> 
> 	cp ./go-dir /usr/local/bin && \
> 
>     sudo sh -c "echo '' >> ~/.zshrc" && \
> 
>     sudo sh -c "cat ./bash/script.sh >> ~/.zshrc" && \
> 
> 	. ~/.zshrc
> 
> 
> 
> ```
> 
> 
> 
> error: 
> 
> ```
> 
> [00:28:40]  📁 /tmp/cdh   main  2s  ✘2 
> 
> $ sudo make build-zsh
> 
> [sudo] password for charon:     
> 
> go build -o go-dir ./main.go && \
> 
> cp ./go-dir /usr/local/bin && \
> 
>     sudo sh -c "echo '' >> ~/.zshrc" && \
> 
>     sudo sh -c "cat ./bash/script.sh >> ~/.zshrc" && \
> 
> . ~/.zshrc
> 
> /bin/sh: 2: /root/.zshrc: Syntax error: "(" unexpected
> 
> make: *** [Makefile:5: build-zsh] Error 2
> 
> ```

It looks like an error in the zahrc file and as if it had already been there, since such a problem could not be reproduced. But thank you, as already described in the readme, in the near future we plan to automate the installation so that you do not need to edit something additionally yourself and there will be a detailed guide with all the problems. It will be in the near future

**Closed as completed** 2024-09-06 18:03 UTC
Labels: bug
